FULL_HD_WIDTH = 1920
FULL_HD_HEIGHT = 1080

CAPTURE_LEFT = int(FULL_HD_WIDTH / 2)
CAPTURE_TOP = 0
CAPTURE_WIDTH = int(FULL_HD_WIDTH / 2)
CAPTURE_HEIGHT = int(FULL_HD_HEIGHT / 2)

CATURE_REGION = (CAPTURE_LEFT, CAPTURE_TOP, CAPTURE_WIDTH, CAPTURE_HEIGHT)
