FULL_HD_WIDTH = 1080
FULL_HD_HEIGHT = 1920

CAPTURE_LEFT = int(FULL_HD_WIDTH / 2)
CAPTURE_TOP = 0
CAPTURE_WIDTH = FULL_HD_WIDTH
CAPTURE_HEIGHT = int(FULL_HD_HEIGHT / 2)

CATURE_REGION = (CAPTURE_LEFT, CAPTURE_TOP, CAPTURE_WIDTH, CAPTURE_HEIGHT)
